name: CI

on:
  push:
    branches:
      - main
      - dev
      - oidc-test
  pull_request:
    branches:
      - main
permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestation.
  contents: read

jobs:
  build-publish-maven:
      runs-on: ubuntu-latest
      env:
        DOCKER_REPO: 'mgm-project-docker-local'
        IMAGE_NAME: 'my-very-cool-image:${{ github.run_number }}'
        JF_URL: https://${{ vars.JF_URL }}/ 
        DOCKER_CLI_EXPERIMENTAL: enabled
        JFROG_PLATFORM_REPO: 'mgm-project-maven-virtual'
        JF_PROJECT: mgm-project

      steps:
          - name: Check out repository
            uses: actions/checkout@v4
        
          - name: Setup JFrog CLI
            id: setup-cli 
            uses: jfrog/setup-jfrog-cli@v4
            env:
                  JF_URL: https://${{ vars.JF_URL }}/
                  JF_PROJECT: mgm-project
            with:
                    oidc-provider-name: oidc-project-config 
                    oidc-audience: oidc-project-aud
                    #oidc-provider-name: mgm-demo 
                    #oidc-audience: mgm-demo-aud
         
          - name: Validate Connection
            run: |
                  jf rt ping
                  echo "Sucessfully Authenticated."
                  echo "Sleep 60000" 
